crm_asobatapa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', include('common.urls')),
    path('usuarios/', include('users.urls')),
    path('inventario/', include('inventory.urls')),
    path('pagos/', include('payments.urls')),
    path('', RedirectView.as_view(url='inicio/prehome', permanent=False), name='root'),

    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    agregar_detalle_compra,
    obtener_detalles_compra,
    eliminar_item_detalle_compra,
    ProviderListView,
    ProviderDetailView,
    ProviderCreateView,
    ProviderUpdateView,
    ProviderDeleteView,
    CategoryListView, 
    CategoryDetailView, 
    CategoryCreateView, 
    CategoryUpdateView, 
    CategoryDeleteView, 
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ShoppingListView,
    ShoppingDetailView,
    FilterProductsByCategoryView,
    ShoppingCreateView,
    ShoppingUpdateView,
    ShoppingDeleteView,
    InventoryListView,
    InventoryDetailView,
    InventoryCreateView,
    InventoryUpdateView,
    InventoryDeleteView,
    OrdenServicioListView,
    OrdenServicioDetailView,
    OrdenServicioCreateView,
    OrdenServicioUpdateView,
    OrdenServicioDeleteView
)
app_name = 'inventory'
urlpatterns = [
    path('proveedores/', ProviderListView.as_view(), name='provider_list'),
    path('proveedores/<int:pk>/', ProviderDetailView.as_view(), name='provider_detail'),
    path('proveedores/new/', ProviderCreateView.as_view(), name='provider_create'),
    path('proveedores/<int:pk>/edit/', ProviderUpdateView.as_view(), name='provider_edit'),
    path('proveedores/<int:pk>/delete/', ProviderDeleteView.as_view(), name='provider_delete'),

    path('categorias/', CategoryListView.as_view(), name='category_list'),
    path('categorias/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categorias/new/', CategoryCreateView.as_view(), name='category_create'),
    path('categorias/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_edit'),
    path('categorias/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    #CRUD PRODUCTO

    path('productos/', ProductListView.as_view(), name='product_list'),
    path('productos/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('productos/new/', ProductCreateView.as_view(), name='product_create'),
    path('productos/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_edit'),
    path('productos/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

    #CRUD COMPRAS

    path('compras/', ShoppingListView.as_view(), name='shopping_list'),
    path('compras/<int:pk>/', ShoppingDetailView.as_view(), name='shopping_detail'),
    path('compras/new/', ShoppingCreateView.as_view(), name='shopping_create'),
    path('compras/filter-products/', FilterProductsByCategoryView.as_view(), name='filter_products_by_category'),
    path('compras/<int:pk>/edit/', ShoppingUpdateView.as_view(), name='shopping_edit'),
    path('compras/<int:pk>/delete/', ShoppingDeleteView.as_view(), name='shopping_delete'),

    path('compras/<int:compra_id>/agregar_detalle_compra/', agregar_detalle_compra, name='agregar_detalle_compra'),
    path('compras/obtener_detalles_compra/<int:compra_id>/', obtener_detalles_compra, name='obtener_detalles_compra'),
    path('compras/eliminar_detalle_compra/<int:item_compra_id>/', eliminar_item_detalle_compra, name='eliminar_item_detalle_compra'),
    #CRUD PRODUCTO

    path('inventarios/', InventoryListView.as_view(), name='inventory_list'),
    path('inventarios/<int:pk>/', InventoryDetailView.as_view(), name='inventory_detail'),
    path('inventarios/new/', InventoryCreateView.as_view(), name='inventory_create'),
    path('inventarios/<int:pk>/edit/', InventoryUpdateView.as_view(), name='inventory_edit'),
    path('inventarios/<int:pk>/delete/', InventoryDeleteView.as_view(), name='inventory_delete'),

     #CRUD ORDENES DE SERVICIO

    path('orden-servicio/', OrdenServicioListView.as_view(), name='service_list'),
    path('orden-servicio/<int:pk>/', OrdenServicioDetailView.as_view(), name='service_detail'),
    path('orden-servicio/new/', OrdenServicioCreateView.as_view(), name='service_create'),
    path('orden-servicio/<int:pk>/edit/', OrdenServicioUpdateView.as_view(), name='service_edit'),
    path('orden-servicio/<int:pk>/delete/', OrdenServicioDeleteView.as_view(), name='service_delete'),
]

payments/urls.py
from django.urls import path
from payments.views import (
    GenerateInvoiceForSuscriberView, 
    SearchSuscriberView, 
    pay_invoice,
    cancelled_invoice,
    create_invoice_extraordinary,
    print_invoice,
    GenerateInvoicePDFsView, 
    AddPaymentView, 
    RenderInvoiceView, 
    InvoiceList,
    InvoiceDetailView,
    InvoiceCreateView
)

app_name = 'payments'
urlpatterns = [
    # ... Otras URLs ...
    path('generate_invoice_pdf/<int:id_suscriber>/', GenerateInvoiceForSuscriberView.as_view(), name='generate_invoice_pdf'),
    path('search/', SearchSuscriberView.as_view(), name='search_suscriber'),
    path('generate-pdf/list/', GenerateInvoicePDFsView.as_view(), name='invoice_list'),
    path('add-payment/<int:suscriber_id>/', AddPaymentView.as_view(), name='add_payment'),
    path('test/<int:id_suscriber>/', RenderInvoiceView.as_view(), name='test'),
    path('historico-factura/<int:id_suscriber>/', InvoiceList.as_view(), name='view_invoice_list'),
    path('historico-factura/detalle/<int:id_invoice>/', InvoiceDetailView.as_view(), name='view_invoice_detail'),
    path('pagar-factura/<int:invoice_id>/', pay_invoice, name='pay_invoice'),
    path('anular-factura/<int:invoice_id>/', cancelled_invoice, name='cancelled_invoice'),
    path('crear-recibo-extemporaneo/', create_invoice_extraordinary, name='create_invoice_extra'),
    path('imprimir-recibo-extemporaneo/<int:invoice_id>', print_invoice, name='print_invoice_extra'),
    path('crear-factura/<int:pk>/', InvoiceCreateView.as_view(), name='create_invoice_pdf'),

    ]

users/urls.py
from django.contrib import admin
from django.urls import path
from users.views import (
    CustomLoginView, 
    CustomLogoutView, 
    CustomDashboardView, 
    SuscriberListView, 
    SuscriberDetailView, 
    SuscriberCreateView, 
    SuscriberUpdateView, 
    SuscriberDeleteView,
    SuscriberListDelinquent,
    MonthlyIncomeView,
    suspended_suscriber,
    enable_suscriber,
    )
app_name = 'transversal'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('dashboard', CustomDashboardView.as_view(), name='dashboard'),
    path('monthly-income/', MonthlyIncomeView.as_view(), name='monthly_income'),
    path('suscriptores/', SuscriberListView.as_view(), name='suscriber_list'),
    path('suscriptores/<int:pk>/', SuscriberDetailView.as_view(), name='suscriber_detail'),
    path('suscriptores/new/', SuscriberCreateView.as_view(), name='suscriber_create'),
    path('suscriptores/<int:pk>/edit/', SuscriberUpdateView.as_view(), name='suscriber_edit'),
    path('suscriptores/<int:pk>/eliminar/', SuscriberDeleteView.as_view(), name='suscriber_delete'),
    path('suscriptores/en-mora', SuscriberListDelinquent.as_view(), name='suscribers_delinquent'),
    path('suscriptores/suspender-servicio/<int:suscriber_id>', suspended_suscriber, name='suspender_servicio'),
    path('suscriptores/habilitar-servicio/<int:suscriber_id>', enable_suscriber, name='habilitar_servicio'),

]

crm_asobatapa/templates/base_home.html
{% load static %}
<!doctype html>
<html lang="es">
    <head>
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-TXNRP623');</script>
            <!-- End Google Tag Manager -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
        <title>
            Sistema de Compras, Facturación e Inventarios
        </title>
        
        <meta name="description" content="Administración, inventarios, facturación, contol de caja, Sistema de compras, facturación e inventario">
        <meta name="author" content="Backend Developer - Dehibi Blandón">
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />

        <link href="{% static 'home_page/assets/css/bootstrap.css' %}" rel="stylesheet" />
        <link href="{% static 'home_page/assets/css/landing-page.css' %}" rel="stylesheet"/>

        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300' rel='stylesheet' type='text/css'>
        <link href="{% static 'home_page/assets/css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    </head>
    <body class="landing-page landing-page2">
          <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TXNRP623"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
        <nav class="navbar navbar-transparent navbar-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
         
                    <div class="buttons">
                        <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">

                        <a href="{% url 'transversal:login' %}" class="btn btn-fill btn-neutral">
                            <i class="fa fa-user"></i> Iniciar Sesión
                        </a>
                    </div>
                    </button>
                    <a href="">
                        <div class="logo-container">
                            <div class="logo">
                                <img src="/media/{{company_logo}}" alt="Logo {{company_name}}">
                            </div>
                            <div class="brand">
                                {{company_name}}
                            </div>
                        </div>
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="example" >
                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <div class="buttons">
                                <a href="{% url 'transversal:login' %}" class="btn btn-fill btn-neutral">
                                    <i class="fa fa-user"></i> Iniciar Sesión
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
        </nav>
        <div class="wrapper">
        {% block content_home %}

        {% endblock %}
        
    </div>
    </body>

    </html>
    

crm_asobatapa/templates/base_home_prehome.html
{% load static %}
<!doctype html>
<html lang="es">
    <head>
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-TXNRP623');</script>
        <!-- End Google Tag Manager -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
        <title>
            Sistema de Compras, Facturación e Inventarios
        </title>
        
        <meta name="description" content="Administración, inventarios, facturación, contol de caja, Sistema de compras, facturación e inventario">
        <meta name="author" content="Backend Developer - Dehibi Blandón">
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />

        <link href="{% static 'home_page/assets/css/bootstrap.css' %}" rel="stylesheet" />
        <link href="{% static 'home_page/assets/css/landing-page.css' %}" rel="stylesheet"/>

        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300' rel='stylesheet' type='text/css'>
        <link href="{% static 'home_page/assets/css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    </head>
    <body class="landing-page landing-page2">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TXNRP623"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
        <div class="wrapper">
        {% block content_home %}

        {% endblock %}
    
        {% block content_footer %}{% endblock %}
        </div>
    </body>

    </html>
    

crm_asobatapa/templates/navbar_aside.html
      
    {% load static %}
    {% load l10n %}
    <div class="sidenav-header" style="margin-bottom: 20px;">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href="{% url 'transversal:dashboard'%} " >
        {% if user.is_authenticated %}
        <div class="sidenav-content">
          {% if company_logo %}
            <img src="{{ company_logo }}" alt="{{ company_name }}" width="60" height="60">
          {% endif %}
          <p class="ms-1 font-weight-bold">{{ company_name }}</p>            
        </div>
    {% endif %}
      </a>
  </div>
  <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white active bg-gradient-primary " href="{% url 'transversal:dashboard' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard Interactivo</span>
          </a>
        </li>
       <!-- Categoria de menú -->
        <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Registro de pagos</h6>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'payments:invoice_list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">table_view</i>
            </div>
            <span class="nav-link-text ms-1">Emitir Facturas masivas</span>
          </a>
        </li> {% endcomment %}
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'payments:search_suscriber' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">search</i>
            </div>
            <span class="nav-link-text ms-1">Consultar o <br> Registrar Pago</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'transversal:suscribers_delinquent' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">screen_search_desktop</i>
            </div>
            <span class="nav-link-text ms-1">Clientes en Mora</span>
          </a>
        </li>
        <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Suscriptores</h6>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'transversal:suscriber_list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">view_list</i>
            </div>
            <span class="nav-link-text ms-1">Listado de Suscriptores</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'inventory:service_list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">build</i>
            </div>
            <span class="nav-link-text ms-1">Orden de mantenimiento</span>
          </a>
        </li>
        <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Inventarios y Compras</h6>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'inventory:provider_list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">business</i>
            </div>
            <span class="nav-link-text ms-1">Proveedores</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'inventory:category_list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">category</i>
            </div>
            <span class="nav-link-text ms-1">Categorías</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'inventory:product_list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">view_in_ar</i>
            </div>
            <span class="nav-link-text ms-1">Productos</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'inventory:shopping_list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">storefront</i>
            </div>
            <span class="nav-link-text ms-1">Compras</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'inventory:inventory_list' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">inventory</i>
            </div>
            <span class="nav-link-text ms-1">Inventario</span>
          </a>
        </li>


      </ul>
    </div>

crm_asobatapa/templates/navbar_main.html
      {% load static %}
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Inicio</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Página actual</li>
          </ol>
          {% comment %} <h6 class="font-weight-bolder mb-0">Tables</h6> {% endcomment %}
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group input-group-outline">
              <!-- <label class="form-label">Busquemos algo</label>
              <input type="text" class="form-control"> -->
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
            {% if user.is_authenticated %}
            <li class="m-2 nav-item d-flex align-items-center">              
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">{{userlogedname}}</span>             
            </li>
            <li class="nav-item d-flex align-items-center">
              <form id="logout-form" method="POST" action="{% url 'transversal:logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                  <i class="fa fa-sign-out me-sm-1"></i>Cerrar sesión
                </button>
            </form>
            </li>

          {% endif %}
          <!--Ajustar botones de configuración y de notificaciones-->
            {% comment %} <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </a>
            </li>
            <li class="nav-item px-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0">
                <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
              </a>
            </li> {% endcomment %}
            {% comment %} <li class="nav-item dropdown pe-2 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-bell cursor-pointer"></i>
              </a>
              <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="my-auto">
                        <img src="../assets/img/team-2.jpg" class="avatar avatar-sm  me-3 ">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          <span class="font-weight-bold">New message</span> from Laur
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          13 minutes ago
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="my-auto">
                        <img src="../assets/img/small-logos/logo-spotify.svg" class="avatar avatar-sm bg-gradient-dark  me-3 ">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          <span class="font-weight-bold">New album</span> by Travis Scott
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          1 day
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="avatar avatar-sm bg-gradient-secondary  me-3  my-auto">
                        <svg width="12px" height="12px" viewBox="0 0 43 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                          <title>credit-card</title>
                          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g transform="translate(-2169.000000, -745.000000)" fill="#FFFFFF" fill-rule="nonzero">
                              <g transform="translate(1716.000000, 291.000000)">
                                <g transform="translate(453.000000, 454.000000)">
                                  <path class="color-background" d="M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z" opacity="0.593633743"></path>
                                  <path class="color-background" d="M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z"></path>
                                </g>
                              </g>
                            </g>
                          </g>
                        </svg>
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          Payment successfully completed
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          2 days
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
              </ul>
            </li> {% endcomment %}
          </ul>
        </div>
      </div>