crm_asobatapa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', include('common.urls')),
    path('usuarios/', include('users.urls')),
    path('inventario/', include('inventory.urls')),
    path('pagos/', include('payments.urls')),
    path('', RedirectView.as_view(url='inicio/prehome', permanent=False), name='root'),

    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    agregar_detalle_compra,
    obtener_detalles_compra,
    eliminar_item_detalle_compra,
    ProviderListView,
    ProviderDetailView,
    ProviderCreateView,
    ProviderUpdateView,
    ProviderDeleteView,
    CategoryListView, 
    CategoryDetailView, 
    CategoryCreateView, 
    CategoryUpdateView, 
    CategoryDeleteView, 
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ShoppingListView,
    ShoppingDetailView,
    FilterProductsByCategoryView,
    ShoppingCreateView,
    ShoppingUpdateView,
    ShoppingDeleteView,
    InventoryListView,
    InventoryDetailView,
    InventoryCreateView,
    InventoryUpdateView,
    InventoryDeleteView,
    OrdenServicioListView,
    OrdenServicioDetailView,
    OrdenServicioCreateView,
    OrdenServicioUpdateView,
    OrdenServicioDeleteView
)
app_name = 'inventory'
urlpatterns = [
    path('proveedores/', ProviderListView.as_view(), name='provider_list'),
    path('proveedores/<int:pk>/', ProviderDetailView.as_view(), name='provider_detail'),
    path('proveedores/new/', ProviderCreateView.as_view(), name='provider_create'),
    path('proveedores/<int:pk>/edit/', ProviderUpdateView.as_view(), name='provider_edit'),
    path('proveedores/<int:pk>/delete/', ProviderDeleteView.as_view(), name='provider_delete'),

    path('categorias/', CategoryListView.as_view(), name='category_list'),
    path('categorias/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categorias/new/', CategoryCreateView.as_view(), name='category_create'),
    path('categorias/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_edit'),
    path('categorias/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    #CRUD PRODUCTO

    path('productos/', ProductListView.as_view(), name='product_list'),
    path('productos/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('productos/new/', ProductCreateView.as_view(), name='product_create'),
    path('productos/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_edit'),
    path('productos/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

    #CRUD COMPRAS

    path('compras/', ShoppingListView.as_view(), name='shopping_list'),
    path('compras/<int:pk>/', ShoppingDetailView.as_view(), name='shopping_detail'),
    path('compras/new/', ShoppingCreateView.as_view(), name='shopping_create'),
    path('compras/filter-products/', FilterProductsByCategoryView.as_view(), name='filter_products_by_category'),
    path('compras/<int:pk>/edit/', ShoppingUpdateView.as_view(), name='shopping_edit'),
    path('compras/<int:pk>/delete/', ShoppingDeleteView.as_view(), name='shopping_delete'),

    path('compras/<int:compra_id>/agregar_detalle_compra/', agregar_detalle_compra, name='agregar_detalle_compra'),
    path('compras/obtener_detalles_compra/<int:compra_id>/', obtener_detalles_compra, name='obtener_detalles_compra'),
    path('compras/eliminar_detalle_compra/<int:item_compra_id>/', eliminar_item_detalle_compra, name='eliminar_item_detalle_compra'),
    #CRUD PRODUCTO

    path('inventarios/', InventoryListView.as_view(), name='inventory_list'),
    path('inventarios/<int:pk>/', InventoryDetailView.as_view(), name='inventory_detail'),
    path('inventarios/new/', InventoryCreateView.as_view(), name='inventory_create'),
    path('inventarios/<int:pk>/edit/', InventoryUpdateView.as_view(), name='inventory_edit'),
    path('inventarios/<int:pk>/delete/', InventoryDeleteView.as_view(), name='inventory_delete'),

     #CRUD ORDENES DE SERVICIO

    path('orden-servicio/', OrdenServicioListView.as_view(), name='service_list'),
    path('orden-servicio/<int:pk>/', OrdenServicioDetailView.as_view(), name='service_detail'),
    path('orden-servicio/new/', OrdenServicioCreateView.as_view(), name='service_create'),
    path('orden-servicio/<int:pk>/edit/', OrdenServicioUpdateView.as_view(), name='service_edit'),
    path('orden-servicio/<int:pk>/delete/', OrdenServicioDeleteView.as_view(), name='service_delete'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from users.views import (
    CustomLoginView, 
    CustomLogoutView, 
    CustomDashboardView, 
    SuscriberListView, 
    SuscriberDetailView, 
    SuscriberCreateView, 
    SuscriberUpdateView, 
    SuscriberDeleteView,
    SuscriberListDelinquent,
    MonthlyIncomeView,
    suspended_suscriber,
    enable_suscriber,
    )
app_name = 'transversal'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('dashboard', CustomDashboardView.as_view(), name='dashboard'),
    path('monthly-income/', MonthlyIncomeView.as_view(), name='monthly_income'),
    path('suscriptores/', SuscriberListView.as_view(), name='suscriber_list'),
    path('suscriptores/<int:pk>/', SuscriberDetailView.as_view(), name='suscriber_detail'),
    path('suscriptores/new/', SuscriberCreateView.as_view(), name='suscriber_create'),
    path('suscriptores/<int:pk>/edit/', SuscriberUpdateView.as_view(), name='suscriber_edit'),
    path('suscriptores/<int:pk>/eliminar/', SuscriberDeleteView.as_view(), name='suscriber_delete'),
    path('suscriptores/en-mora', SuscriberListDelinquent.as_view(), name='suscribers_delinquent'),
    path('suscriptores/suspender-servicio/<int:suscriber_id>', suspended_suscriber, name='suspender_servicio'),
    path('suscriptores/habilitar-servicio/<int:suscriber_id>', enable_suscriber, name='habilitar_servicio'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from common.models import BaseManage

   
class Sector(BaseManage):
    name_sector = models.CharField(
        verbose_name="Nombre Sector",
        max_length=55,
        blank=False,
        null=False,
        default=''
    )
    def __str__(self):
        return self.name_sector

    class Meta:
        verbose_name = "Sector o Vereda"
        verbose_name_plural = "Sectores o Veredas"
        
class CostActions(BaseManage):
    costo_uniqued_for_action = models.IntegerField(
        verbose_name="Valor de la Acción",
        blank=False,
        null=False,
        default=0
    )
    def __str__(self):
        return str(self.costo_uniqued_for_action)

    class Meta:
        verbose_name = "Valor de la Acción (MATRÍCULA) Definida"

class Actions(BaseManage):
    value_action = models.IntegerField(
        verbose_name="Tarifa Mensual Por Acción",
        blank=False,
        null=False,
        default=0
    )
    property_type = models.CharField(
        max_length=15,
        choices=[
            ('not use', 'No Usa Acción'),
            ('house Alone', 'Vivienda Desocupada'),
            ('house', 'Vivienda'),
            ('Cattle Farm', 'Finca Ganadera'),
            ('Country Farm', 'Finca Campestre'),
            ('Farming Farm', 'Finca Agropecuaria'),
            ('Pork Farm', 'Finca Porcicola'),
            ('Other', 'Otro Negocio'),
        ],
        default='house',
    )

    def get_property_type_display(self):
            for choice in self._meta.get_field('property_type').choices:
                if choice[0] == self.property_type:
                    return choice[1]
            return self.property_type

    def __str__(self):
            return f"{self.get_property_type_display()} - {self.value_action}"

    class Meta:
        verbose_name = "Valor de Uso Por tipo de acción"
        verbose_name_plural = "Valores de Uso Por tipo de acción"

class Suscriber(BaseManage):
    PROPERTY_TYPE_CHOICES = (
        ('not use', 'No Usa'),
        ('house Alone', 'Vivienda Sola'),
        ('house', 'Vivienda'),
        ('Cattle Farm', 'Finca Ganadera'),
        ('Country Farm', 'Finca Campestre'),
        ('Farming Farm', 'Finca Agropecuaria'),
        ('Pork Farm', 'Finca Porcicola'),
        ('Other', 'Otro Negocio'),
    )
    DOCUMENT_TYPE_CHOICES = [
        ('no', 'Seleccionar'),
        ('CC', 'C.C'),
        ('CE', 'C.E'),
    ]
    document_type = models.CharField(
        verbose_name="Tipo de Documento",
        max_length=2,
        choices=DOCUMENT_TYPE_CHOICES,
        default='CC',
    )
    identification_number = models.CharField(
        verbose_name="Documento",
        max_length=255,
        blank=True,
        null=True,
        default=''
    )
    name_suscriber = models.CharField(
        verbose_name="Nombre de suscriptor",
        max_length=255,
        blank=True,
        null=True,
        default=''
    )
    last_name_suscribe = models.CharField(
        verbose_name="Apellido del Suscriptor",
        max_length=255,
        blank=True,
        null=True,
        default=''
    )
    telephone = models.CharField(max_length=15)
    sector_suscriber = models.ForeignKey(
        Sector,
        verbose_name="Sector",
        on_delete=models.CASCADE,
    )
    name_farm = models.CharField(
        verbose_name="Nombre Finca",
        max_length=55,
        blank=False,
        null=False,
        default=''
    )
    stratum = models.CharField(
        verbose_name="Estrato Vivienda",
        max_length=3,
        blank=True,
        null=True,
        default=''
    )
    count_adult_inhabitants = models.IntegerField(
        verbose_name="Cantidad Adultos",
        blank=True,
        null=True,
        default=0
    )
    count_children_inhabitants = models.IntegerField(
        verbose_name="Cantidad Niños",
        blank=True,
        null=True,
        default=0
    )
    cost_action = models.ManyToManyField(
        CostActions,
        blank=True,
        null=True,
        verbose_name= "Costo de la Acción Suscrita"
    )
    affiliated_shares = models.ManyToManyField(
        Actions,
        verbose_name="Cantidad de Suscripciones Asociadas",
        blank=True,
        null=True,
    )
    value_paid_for_action = models.IntegerField(
        verbose_name="Valor qué pagó de la acción al Suscribirse",
        blank=False,
        null=False,
        default=0
    )
    number_cuotes_for_payment = models.IntegerField(
        verbose_name="Cantidad de cuotas a diferir el Pago",
        blank=False,
        null=False,
        default=0
    )
    monthly_value_to_pay = models.IntegerField(
        verbose_name="Tarifa Mensual Servicio (Generado Automáticamente Segun el Tipo de Acción)",
        blank=False,
        null=False,
        default=0
    )
    pending_balance = models.DecimalField(
        verbose_name="Saldo Pendiente por el Costo de Acción (Generado Automáticamente)",
        max_digits=10,
        decimal_places=2,
        default=0,
        blank=True,
        null=True
    )
    last_payment_date = models.DateTimeField(
        verbose_name="Fecha de último Pago",
        default='',
        blank=True,
        null=True
    )
    status= models.CharField(
        max_length=20,
        choices=[('active', 'Activo Vigente'), ('suspended', 'Suspendido Mora')],
        default='active',
        verbose_name="Estado de Suscriptor"
    )
    mode_billing = models.CharField(
        max_length=20,
        choices=[('frequently', 'Frecuente'), ('annual', 'Anual')],
        default='frequently',
        verbose_name="Modo de facturación para el suscriptor"
    )
    def __str__(self):
        return self.name_suscriber

    class Meta:
        verbose_name = "Suscriptor"
        verbose_name_plural = "Suscriptores"

    # def update_pending_balance(self):
    #     total_pending = self.payment_set.aggregate(total=models.Sum('total_amount'))['total'] or 0
    #     self.pending_balance = total_pending
    #     self.save()

inventory/templates/product/product_form.html
{% extends 'base.html' %}

{% block content %}

{% comment %} <div class="container-fluid px-2 px-md-4">
  <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('https://images.unsplash.com/photo-1531512073830-ba890ca4eba2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80');">
    <span class="mask bg-gradient-primary opacity-6"></span>
  </div>
  <div class="card card-body mx-3 mx-md-4 mt-n6">
    <div class="row">
      <form role="form" method="post">
      {% csrf_token %}
        <div class="row">
          <div class="col-12 col-xl-6">
            <div class="card card-plain h-100">
              <div class="card-header pb-0 p-3">
                <h6 class="mb-0">Datos personales</h6>
              </div>
              <div class="card-body p-3">
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Tipo de Documento</label>
                  <select name="document_type" class="form-control">
                    {% for choice in suscriber.DOCUMENT_TYPE_CHOICES %}
                      <option value="{{ choice.0 }}" {% if suscriber.document_type == choice.0 %} selected {% endif %}>{{ choice.1 }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="">Documento</label>
                  <input type="text" name="identification_number" class="form-control" value="{{ suscriber.identification_number }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Nombre</label>
                  <input type="text" name="name_suscriber" class="form-control" value="{{ suscriber.name_suscriber }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Apellido</label>
                  <input type="text" name="last_name_suscribe" class="form-control" value="{{ suscriber.last_name_suscribe }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Teléfono</label>
                  <input type="text" name="telephone" class="form-control" value="{{ suscriber.telephone }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Cantidad de Habitantes Adultos</label>
                  <input type="text" name="count_adult_inhabitants" class="form-control" value="{{ suscriber.count_adult_inhabitants }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Cantidad de Habitantes Niños</label>
                  <input type="text" name="count_children_inhabitants" class="form-control" value="{{ suscriber.count_children_inhabitants }}">
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-xl-6">
            <div class="card card-plain h-100">
              <div class="card-header pb-0 p-3">
                <h6 class="mb-0">Información del Inmueble</h6>
              </div>
              <div class="card-body p-3">
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Sector</label>
                  <input type="text" name="sector_suscriber" class="form-control" value="{{ suscriber.sector_suscriber }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Nombre de Finca</label>
                  <input type="text" name="name_finca" class="form-control" value="{{ suscriber.name_finca }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Estrato</label>
                  <input type="text" name="estrato" class="form-control" value="{{ suscriber.estrato }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Tipo de Vivienda</label>
                  <input type="text" name="property_type" class="form-control" value="{{ suscriber.property_type }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Valor a pagar por la acción</label>
                  <input type="text" name="value_action_for_suscriber" class="form-control" value="{{ suscriber.value_action_for_suscriber }}">
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label">Cantidad de Cuotas de pago</label>
                  <input type="text" name="number_cuotes_for_payment" class="form-control" value="{{ suscriber.number_cuotes_for_payment }}">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Registrar Usuario</button>
        </div>
      </form>
    </div>
  </div>
</div> {% endcomment %}

<div class="container-fluid px-2 px-md-4">
  <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('https://images.unsplash.com/photo-1531512073830-ba890ca4eba2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80');">
    <span class="mask bg-gradient-primary opacity-6"></span>
  </div>
  <div class="card card-body mx-3 mx-md-4 mt-n6">
    <div class="row">
      <form role="form" method="post" >
      {% csrf_token %}
        <div class="row">
            <div class="card-header pb-0 p-3">
                <h6 class="mb-0">{% if product %} Editar {% else %} Nuevo {% endif %} Producto</h6>
            </div>
            <div class="col-12 col-xl-6">
            <div class="card card-plain h-100">
              <div class="card-body p-3">
                <div class="mb-3 form-group">
                  <label for="id_document_type">Categoria Asociada</label>
                  <div class="input-group input-group-outline">
                      {{form.category}}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-xl-6">
            <div class="card card-plain h-100">
              <div class="card-body p-3">
                <div class="mb-3 form-group">
                  <label for="id_document_type">Nombre</label>
                  <div class="input-group input-group-outline">
                      {{form.name}}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-xl-6">
            <div class="card card-plain h-100">
              <div class="card-body p-3">
                <div class="mb-3 form-group">
                  <label for="id_sector_suscriber">Descripción</label>
                  <div class="input-group input-group-outline">
                  {{form.description}}
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary"><span class="fa fa-save"></span> Guardar</button>
          <a href="{% url 'inventory:product_list' %}" class="btn btn-success"><span class="fa fa-undo"></span> Cancelar</a>
        </div>
      </form>
    </div>
  </div>
</div>


{% endblock %}

{% block javascript %}{% endblock %}

inventory/templates/product/product_list.html
{% extends 'base.html' %}

{% block content %}
    <!-- Pantilla -->
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card my-4">
                    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                        <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                            <div class="row">
                                <div class="col-9">
                                    <h6 class="text-white text-capitalize ps-3 mt-2">Listado de Productos</h6>
                                </div>
                                <div class="col-3 d-flex justify-content-between align-items-center">
                                    <a href="{% url 'inventory:product_create' %}" class="btn btn-info btn-circle" role="button">
                                        <i class="far fa-new"></i>Nuevo Producto
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if not products %}
                        <p>No hay Productos Creados</p>
                    {% else %}
                        <div class="card-body px-0 pb-2">
                            <div class="table-responsive p-0">
                                <table id="datatable" class="table align-items-center mb-0">
                                    <thead>
                                    <tr style="text-align:center; font-size:13px">
                                        <th>Id</th>
                                        <th>Nombre</th>
                                        <th>Categoría</th>
                                        <th class="all">Acciones</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for product in products %}
                                        <tr style="text-align:center; font-size:13px">
                                            <td>{{ product.id }}</td>
                                            <td>{{ product.name }}</td>
                                            <td>{{ product.category }}</td>

                                            <td>                                             
                                                <div class="d-flex align-items-center justify-content-center">
                                                  <a href="{% url 'inventory:product_edit' product.id %}" class="btn btn-warning btn-circle me-2" role="button">
                                                      <i class="far fa-edit"></i>
                                                  </a>

                                                  <form id="deleteForm" method="post" action="{% url 'inventory:product_delete' product.id %}">
                                                      {% csrf_token %}
                                                      <!-- Otros campos del formulario, si los hay -->
                                                      <a id="btn_delete" type="submit" class="btn btn-danger btn-circle" data-target-delete="{% url 'inventory:product_delete' product.id %}">
                                                          <i class="far fa-trash-alt"></i>
                                                      </a>
                                                  </form>
                                              </div>
                                          </td>

                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        // Inicializar DataTable
        var table = $('#datatable').DataTable({
            "paging": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "lengthChange": true,
            "language": {
                "decimal": ",",
                "thousands": ".",
                "sProcessing":    "Procesando...",
                "sLengthMenu":    "Mostrar _MENU_ registros",
                "sZeroRecords":   "No se encontraron resultados",
                "sEmptyTable":    "Ningún dato disponible en esta tabla",
                "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":   "",
                "sSearch":        "Buscar:",
                "sUrl":           "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
        const btn_delete = document.querySelectorAll("#btn_delete")
        btn_delete.forEach(btn => {
          btn.addEventListener('click' , function(event){
            const data_target_delete = btn.getAttribute("data-target-delete")
            const csrf_token = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
            const fullUrl = `${window.location.origin}${data_target_delete}`;

            Swal.fire({
                title: "Está seguro de eliminar El Producto?",
                showDenyButton: true,
                showCancelButton: false,
                confirmButtonText: "Eliminar",
                denyButtonText: `Cancelar`
              }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                  if (result.isConfirmed) {
                        // Realiza la solicitud AJAX
                        fetch(data_target_delete, {
                            method: 'DELETE',
                            headers: {
                                'X-CSRFToken': csrf_token,
                            },
                        })
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                Swal.fire("Producto eliminado exitosamente", "", "success")
                                    .then(() => {
                                        window.location.href = '{{ success_url }}';
                                    });
                            } else {
                                Swal.fire("Error al eliminar el Producto", data.message, "error");
                            }
                        });
                    } else if (result.isDenied) {
                        Swal.fire("El producto no fue Eliminado", "", "info");
                    }
              });
          })
        })
    });
</script>
{% endblock %}